version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: workflow_postgres_test
    environment:
      POSTGRES_DB: workflow_platform_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d workflow_platform_test"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
