name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend deps
        working-directory: ./frontend
        run: |
          npm ci

      - name: Lint and typecheck frontend
        working-directory: ./frontend
        run: |
          npm run lint
          npm run typecheck

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm run build

      - name: Install backend deps
        working-directory: ./backend
        run: |
          npm ci

      - name: Lint and typecheck backend
        working-directory: ./backend
        run: |
          npm run lint || echo "Lint errors (non-blocking)"
          npm run typecheck

      - name: Build backend
        working-directory: ./backend
        run: |
          npm run build

  docker:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ai-workflow-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ai-workflow-backend:latest
